### モジュールのインポート

In [1]:
from yikit.feature_selection import BorutaPy
from sklearn.datasets import load_diabetes
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

### サンプルデータの取得

In [2]:
diabetes = load_diabetes()
X = pd.DataFrame(diabetes['data'], columns = diabetes['feature_names'])
y = pd.Series(diabetes['target'])
X.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

### 削減してみる

In [3]:
selector = BorutaPy(RandomForestRegressor(n_jobs=-1, random_state=334), random_state=334, n_jobs=-1, perc='auto', verbose=1)
selector.fit(X, y)
X_selected = X.loc[:, selector.get_support()]
X_selected.head()

Calc r_ccmax:   0%|          | 0/10000 [00:00<?, ?it/s]

2026-10-14 12:21:11,071 - yikit.feature_selection._wrapper:482[INFO] - Assigned perc = 80.2

BorutaPy:   0%|          | 0/100 [00:00<?, ?it/s]

2026-10-14 12:21:15,255 - yikit.feature_selection._wrapper:544[INFO] -

BorutaPy finished running.

Iteration: 	100 / 100
Confirmed: 	5
Tentative: 	1
Rejected: 	4

        bmi        bp        s2        s5        s6
0  0.061696  0.021872 -0.034821  0.019907 -0.017646
1 -0.051474 -0.026328 -0.019163 -0.068332 -0.092204
2  0.044451 -0.005670 -0.034194  0.002861 -0.025930
3 -0.011595 -0.036656  0.024991  0.022688 -0.009362
4 -0.036385  0.021872  0.015596 -0.031988 -0.046641

In [4]:
selector.get_support()

array([False, False,  True,  True, False,  True, False, False,  True,
        True])

```perc="auto"```で決まった百分位

In [5]:
selector.perc_

80.15061914920807